# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Kubesec

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '36 8 * * 3'

jobs:
  setup:
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Collect all yaml
        id: list_yaml
        # run: echo '::set-output name=value::$(find . -type f -name "*.yaml")'
        run: |
          LIST_YAML="$(find . -type f -name '*.yaml')"
          echo "::set-output name=value::$(IFS=$','; echo $LIST_YAML | jq -cnR '[inputs | select(length>0)]')"
          # echo "::set-output name=value::\"$LIST_YAML\""
          # echo $LIST_YAML

    outputs:
      matrix: ${{ steps.list_yaml.outputs.value }}

  lint:
    needs: [ setup ]
    name: Kubesec
    runs-on: ubuntu-20.04
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy: 
      # matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
      matrix: 
        # value: ["all.yml", "all4.yml"]
        # value: ${{ needs.setup.outputs.matrix }} 
        value: ${{ fromJson(needs.setup.outputs.matrix) }}
        # value: ${{ needs.setup.outputs.matrix }}
        # value: ${{ env.LIST_YAML }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run kubesec scanner
        uses: controlplaneio/kubesec-action@43d0ddff5ffee89a6bb9f29b64cd865411137b14
        with:
          input: ${{ matrix.value }}
          format: template
          template: template/sarif.tpl
          # output: ${{ matrix.value }}.sarif
          output: /tmp/kubesec.sarif
          exit-code: "0"

      - name: Print out the output
        if: ${{ env.ACT }}
        run: cat ${{ matrix.value }}.sarif

      - name: Upload Kubesec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        if: ${{ !env.ACT }}
        with:
          # sarif_file: ${{ matrix.value }}.sarif
          sarif_file: /tmp/kubesec.sarif
